services:
  ackee:
    image: electerious/ackee
    container_name: ackee
    restart: always
    ports:
      - "3009:3000"
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee
      - ACKEE_USERNAME=username
      - ACKEE_PASSWORD=password
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
