name: semaphore
services:
    semaphore:
        ports:
            - 3000:3000
        container_name: semaphore
        environment:
            - SEMAPHORE_DB_DIALECT=bolt
            - SEMAPHORE_ADMIN=admin
            - SEMAPHORE_ADMIN_PASSWORD=changeme
            - SEMAPHORE_ADMIN_NAME=Admin
            - SEMAPHORE_ADMIN_EMAIL=admin@localhost
        image: semaphoreui/semaphore:latest