# named volume 'answer-data' is marked as "external" (used by service 'answer'), so either remove "external" from volume definition or it needs to be created using: docker volume create answer-data
name: answer
services:
    answer:
        ports:
            - 9080:80
        volumes:
            - answer-data:/data
        container_name: answer
        image: apache/answer:latest
volumes:
    answer-data:
        external: true
        name: answer-data