name: appwrite

services:
  appwrite:
    image: appwrite/appwrite:1.8.0
    stdin_open: true
    tty: true
    entrypoint:
      - install
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appwrite:/usr/src/code/appwrite:rw
