name: arcadedb
services:
    arcadedb:
        ports:
            - 2480:2480
            - 2424:2424
        environment:
            - JAVA_OPTS=-Darcadedb.server.rootPassword=playwithdata
              -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}
        image: arcadedata/arcadedb:latest