# image: https://hub.docker.com/r/dbeaver/cloudbeaver
# config docs: https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#automatic-server-configuration

version: "3.8"

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.5
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace

networks:
  default:
    name: app-network
    external: true

volumes:
  cloudbeaver:
