version: "3.9"

services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    ports:
      - "8111:80"
      - "4431:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
