services:
  caddy:
    image: caddy:latest
    container_name: caddy
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
