services:

  app:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
    volumes:
      - ${VOLUME_STORAGE:-/mnt/volumes}/firefly/upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8870:8080
    expose:
      - 8870
    depends_on:
      - db
  
  db:
    image: mariadb:11.5
    container_name: firefly-db
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=MySecretDatabasePassword # if changed --> also update in .env file
      - MYSQL_DATABASE=firefly
    volumes:
      - ${VOLUME_STORAGE:-/mnt/volumes}/firefly/mysql:/var/lib/mysql